version: '3.8'
services:
  mongodb:
    image: mongo:5.0.8
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-password}
      MONGO_PORT: ${MONGO_PORT:-27017}
    volumes:
      - mongo_data:/data/db
    command: mongod --auth --bind_ip_all
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - container-network
  
  client:
    image: client
    environment:
      - REACT_APP_API_URL=http://server:8080
    ports:
      - '3000:3000'
  server:
    image: server
    environment: 
      MONGODB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME:-root}
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-password}
      MONGODB_HOST: mongodb
      MONGO_PORT: 27017
    ports:
      - '8080:8080'
    networks:
      - container-network

volumes:
  mongo_data:

networks: 
  container-network:
    name: container-network
    driver: bridge

