name: Deploy to Client & Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd reAxion
            git checkout main
            git pull origin main
            /home/github/.volta/bin/npx nx run-many --target=deploy --parallel --projects=server,client
            MONGO_PORT=27017 MONGODB_ROOT_USERNAME=${{ secrets.MONGODB_ROOT_USERNAME }} MONGODB_ROOT_PASSWORD=${{ secrets.MONGODB_ROOT_PASSWORD }}  docker-compose -f docker-compose.prod.yml up -d
